# vim: set filetype=sh:

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

if [ -f $(brew --prefix)/bin/ctags ]; then
  alias ctags="`brew --prefix`/bin/ctags"
fi

if [ -f ~/.asdf/asdf.sh ]; then
  . ~/.asdf/asdf.sh
  . ~/.asdf/completions/asdf.bash
fi

# keep using bash in Catalina or newer
export BASH_SILENCE_DEPRECATION_WARNING=1

export GPG_TTY=$(tty)
